In [1]:
#使用するライブラリをimport
from sqlalchemy import create_engine
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
engine = create_engine("postgresql+psycopg2://analyser:***@localhost:5432/test_db")

In [2]:
#生データを読み込み
path = '../data/raw/Milling_Tool_Dataset.csv'
df = pd.read_csv(path)
#indexを追加
df['index'] = range(0,1400)
#SQLに変換
df.to_sql('sql_dataset', engine, if_exists='replace', index=False)

400

eda.ipynbから、データが時系列データであることが可能性が高いため、移動平均を作成する。

In [3]:
#20行の移動平均を追加したDataFrameを作成
mv_avg_20_df = pd.read_sql_query(
    '''
    SELECT AVG(vibration_x)OVER(ORDER BY index ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS mv_avg_vib_x,
           AVG(vibration_y)OVER(ORDER BY index ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS mv_avg_vib_y,
           AVG(vibration_z)OVER(ORDER BY index ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS mv_avg_vib_z,
           AVG(acoustic_rms)OVER(ORDER BY index ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS mv_avg_ar,
           AVG(spindle_load)OVER(ORDER BY index ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS mv_avg_sl,
           tool_wear
    FROM sql_dataset
    ''',engine)
#相関関係を確認
sns.pairplot(mv_avg_20_df)
plt.savefig("../outputs/figures/data_processing/add_mv_avg_20_pairplot.png", format="png")
plt.close()

各センサの移動平均と"tool_wear"に正の相関関係があることがわかる。
特に"mv_avg_ar", "mv_avg_sl"と非常に強い相関があることが読み取れる。

In [4]:
#相関係数を確認
mv_avg_20_df.corr()

,mv_avg_vib_x,mv_avg_vib_y,mv_avg_vib_z,mv_avg_ar,mv_avg_sl,tool_wear
mv_avg_vib_x,1.000000,0.560811,0.420695,0.790279,0.770665,0.813881
mv_avg_vib_y,0.560811,1.000000,0.382946,0.680138,0.643909,0.701319
mv_avg_vib_z,0.420695,0.382946,1.000000,0.501405,0.489300,0.502900
mv_avg_ar,0.790279,0.680138,0.501405,1.000000,0.918851,0.985153
mv_avg_sl,0.770665,0.643909,0.489300,0.918851,1.000000,0.936610
tool_wear,0.813881,0.701319,0.502900,0.985153,0.936610,1.000000

"mv_avg_ar", "mv_avg_sl"と"tool_wear"は非常に相関が強いことが確認できた。

他センサの移動平均にも強い相関があることが確認できた。

さらにデータ数を減らした移動平均を作成し、"tool_wear"との相関を確認する。

In [5]:
#10行の移動平均を追加したDataFrameを作成
mv_avg_10_df = pd.read_sql_query(
    '''
    SELECT AVG(vibration_x)OVER(ORDER BY index ROWS BETWEEN 9 PRECEDING AND CURRENT ROW) AS mv_avg_vib_x,
           AVG(vibration_y)OVER(ORDER BY index ROWS BETWEEN 9 PRECEDING AND CURRENT ROW) AS mv_avg_vib_y,
           AVG(vibration_z)OVER(ORDER BY index ROWS BETWEEN 9 PRECEDING AND CURRENT ROW) AS mv_avg_vib_z,
           AVG(acoustic_rms)OVER(ORDER BY index ROWS BETWEEN 9 PRECEDING AND CURRENT ROW) AS mv_avg_ar,
           AVG(spindle_load)OVER(ORDER BY index ROWS BETWEEN 9 PRECEDING AND CURRENT ROW) AS mv_avg_sl,
           tool_wear
    FROM sql_dataset
    ''',engine)

sns.pairplot(mv_avg_10_df)
plt.savefig("../outputs/figures/data_processing/add_mv_avg_10_pairplot.png", format="png")
plt.close()

mv_avg_10_df.corr()

,mv_avg_vib_x,mv_avg_vib_y,mv_avg_vib_z,mv_avg_ar,mv_avg_sl,tool_wear
mv_avg_vib_x,1.000000,0.387886,0.284491,0.689059,0.660188,0.713043
mv_avg_vib_y,0.387886,1.000000,0.255374,0.547129,0.473333,0.574725
mv_avg_vib_z,0.284491,0.255374,1.000000,0.379364,0.364937,0.383340
mv_avg_ar,0.689059,0.547129,0.379364,1.000000,0.839041,0.971416
mv_avg_sl,0.660188,0.473333,0.364937,0.839041,1.000000,0.878806
tool_wear,0.713043,0.574725,0.383340,0.971416,0.878806,1.000000

In [6]:
#5行の移動平均を追加したDataFrameを作成
mv_avg_5_df = pd.read_sql_query(
    '''
    SELECT AVG(vibration_x)OVER(ORDER BY index ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS mv_avg_vib_x,
           AVG(vibration_y)OVER(ORDER BY index ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS mv_avg_vib_y,
           AVG(vibration_z)OVER(ORDER BY index ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS mv_avg_vib_z,
           AVG(acoustic_rms)OVER(ORDER BY index ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS mv_avg_ar,
           AVG(spindle_load)OVER(ORDER BY index ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS mv_avg_sl,
           tool_wear
    FROM sql_dataset
    ''',engine)

sns.pairplot(mv_avg_5_df)
plt.savefig("../outputs/figures/data_processing/add_mv_avg_5_pairplot.png", format="png")
plt.close()

mv_avg_5_df.corr()

,mv_avg_vib_x,mv_avg_vib_y,mv_avg_vib_z,mv_avg_ar,mv_avg_sl,tool_wear
mv_avg_vib_x,1.000000,0.223290,0.175501,0.560123,0.486039,0.585956
mv_avg_vib_y,0.223290,1.000000,0.160497,0.412421,0.324381,0.444198
mv_avg_vib_z,0.175501,0.160497,1.000000,0.282359,0.222745,0.281924
mv_avg_ar,0.560123,0.412421,0.282359,1.000000,0.720561,0.939676
mv_avg_sl,0.486039,0.324381,0.222745,0.720561,1.000000,0.787595
tool_wear,0.585956,0.444198,0.281924,0.939676,0.787595,1.000000

In [7]:
#3行の移動平均を追加したDataFrameを作成
mv_avg_2_df = pd.read_sql_query(
    '''
    SELECT AVG(vibration_x)OVER(ORDER BY index ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS mv_avg_vib_x,
           AVG(vibration_y)OVER(ORDER BY index ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS mv_avg_vib_y,
           AVG(vibration_z)OVER(ORDER BY index ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS mv_avg_vib_z,
           AVG(acoustic_rms)OVER(ORDER BY index ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS mv_avg_ar,
           AVG(spindle_load)OVER(ORDER BY index ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS mv_avg_sl,
           tool_wear
    FROM sql_dataset
    ''',engine)

sns.pairplot(mv_avg_2_df)
plt.savefig("../outputs/figures/data_processing/add_mv_avg_2_pairplot.png", format="png")
plt.close()

mv_avg_2_df.corr()

,mv_avg_vib_x,mv_avg_vib_y,mv_avg_vib_z,mv_avg_ar,mv_avg_sl,tool_wear
mv_avg_vib_x,1.000000,0.086282,0.087633,0.365491,0.283881,0.417660
mv_avg_vib_y,0.086282,1.000000,0.073810,0.267628,0.172085,0.288461
mv_avg_vib_z,0.087633,0.073810,1.000000,0.189312,0.119241,0.179036
mv_avg_ar,0.365491,0.267628,0.189312,1.000000,0.531297,0.861699
mv_avg_sl,0.283881,0.172085,0.119241,0.531297,1.000000,0.630145
tool_wear,0.417660,0.288461,0.179036,0.861699,0.630145,1.000000

In [8]:
#各移動平均データを保存
mv_avg_20_df.to_csv('../data/processed/mv_avg_20.csv', encoding = 'utf-8-sig', index=False)
mv_avg_10_df.to_csv('../data/processed/mv_avg_10.csv', encoding = 'utf-8-sig', index=False)
mv_avg_5_df.to_csv('../data/processed/mv_avg_5.csv', encoding = 'utf-8-sig', index=False)
mv_avg_2_df.to_csv('../data/processed/mv_avg_2.csv', encoding = 'utf-8-sig', index=False)

過去のデータ数が少なくなるにつれて作成した移動平均と"tool_wear"との相関が低くなることが確認できた。

他にも１回の加工データから"tool_wear"との相関が強い特徴量を生成可能かトライする。

In [9]:
add_features_df = pd.read_sql_query(
    '''
    SELECT vibration_x+vibration_y+vibration_z AS vib_vec,
           vibration_x+vibration_y AS pl_vib_vec,
           SQRT(POW(vibration_x,2)+POW(vibration_y,2)+POW(vibration_z,2)) AS mag_vec,
           acoustic_rms*spindle_load AS ac_sp,
           ABS(vibration_x) AS abs_vib_x,
           LN(acoustic_rms) AS log_acrms,
           LN(spindle_load) AS log_spload,
           POW(acoustic_rms,2) AS l_acrms,
           POW(spindle_load,2) AS l_spload,
           tool_wear
    FROM sql_dataset
    ''',engine)

sns.pairplot(add_features_df)
plt.savefig("../outputs/figures/data_processing/add_features_pairplot.png", format="png")
plt.close()

add_features_df.corr()

,vib_vec,pl_vib_vec,mag_vec,ac_sp,abs_vib_x,log_acrms,log_spload,l_acrms,l_spload,tool_wear
vib_vec,1.000000,0.826616,0.470910,0.308722,0.338486,0.306616,0.197948,0.307387,0.198372,0.357630
pl_vib_vec,0.826616,1.000000,0.487112,0.299187,0.426999,0.290924,0.199295,0.296075,0.195378,0.359194
mag_vec,0.470910,0.487112,1.000000,0.167639,0.615438,0.156715,0.115417,0.164105,0.110811,0.179101
ac_sp,0.308722,0.299187,0.167639,1.000000,0.168618,0.851103,0.792370,0.858238,0.797586,0.767011
abs_vib_x,0.338486,0.426999,0.615438,0.168618,1.000000,0.156631,0.121844,0.162317,0.119249,0.189286
log_acrms,0.306616,0.290924,0.156715,0.851103,0.156631,1.000000,0.377071,0.985380,0.375596,0.761560
log_spload,0.197948,0.199295,0.115417,0.792370,0.121844,0.377071,1.000000,0.379881,0.988358,0.492632
l_acrms,0.307387,0.296075,0.164105,0.858238,0.162317,0.985380,0.379881,1.000000,0.380341,0.763883
l_spload,0.198372,0.195378,0.110811,0.797586,0.119249,0.375596,0.988358,0.380341,1.000000,0.489757
tool_wear,0.357630,0.359194,0.179101,0.767011,0.189286,0.761560,0.492632,0.763883,0.489757,1.000000

振動ベクトルの長さ、平面振動ベクトルの長さ、振動ベクトルの大きさ、振動の絶対値化、音響データやスピンドル負荷の増幅など、ある程度の派生特徴を試したが、あまり相関が強い特徴は作成できなかった。

計算に使用した特徴よりも相関係数が高くなった"pl_vib_vec"(平面振動ベクトルの長さ)を各センサデータに追加したデータセットを保存する。

In [10]:
add_plane_vec_df = pd.read_sql_query(
    '''
    SELECT vibration_x+vibration_y AS pl_vib_vec,
           vibration_x, vibration_y, vibration_z, acoustic_rms, spindle_load, tool_wear
    FROM sql_dataset
    ''',engine)

add_plane_vec_df.to_csv('../data/processed/add_plane_vec.csv', encoding = 'utf-8-sig', index=False)